name: pypi

on:
  release:
    types: [published]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@186232109eade3d22bfe1bca29ac9a1312598511
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
